on:
  push:
    branches:    
      - master
      
  workflow_dispatch:
  
name: Build and Publish abertschi.ch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Build webapp
      run: |
        make webapp/setup
        make webapp/build
     
    - name: Build hugo
      run: |
        make hugo/build
      
    - name: List output files
      run: ls -al
      

    - name: deploy
      if: github.ref == 'refs/heads/main'
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: build
        METHOD: sftp
        PORT: 5544
        ARGS: --delete
      with:  
        server: ${{ secrets.server }} 
        username: ${{ secrets.username }} 
        password: ${{ secrets.password }}
        protocol: sftp
        port: 5544
        server-dir: ./test
        local-dir: ./public
        dry-run: true
